### PR TITLE
Migrated from jQuery to SuperAgent and Browser Support

### PR DESCRIPTION
**Pull request by pbruna**
Hi,
This pull request change jQuery for [SuperAgent](https://visionmedia.github.io/superagent/), this way is possible to use js-zimbra from the browser and from nodejs.

Also made possible to setup as optional:
- Debug, and
- Timeout

### CODE REVIEW

**Comment by ghost** [comment]
@dploeger can you look at this?

**Comment by dploeger** [comment]
Will do.

**Comment by dploeger** [comment]
Hi @pbruna. Thank you very much. You have put a lot of effort in this.

Sadly, I'm terribly sorry, but I can not accept the pull request, because of the following things:
- I don't know, where you've got that jQuery-snippet. JS-Zimbra was originally depending on Restler and is now depending on Unirest, which should also work from the browser.
- You can already change the log level by configuring the Winston logger "js-zimbra". See [here](https://github.com/winstonjs/winston#working-with-multiple-loggers-in-winston) for details about this. Encapsuling all logging requests with a conditional is certainly not the best way to accomplish that. :)
- You have lowercased the module exports for all errors. Actually, there's currently a "glitch" in the source code, because all returned errors should actually be instances of the error. (So the "new" prefix is missing) And with this, eslint considers errors as classes and requires classes to be upper case. So they really should be upper case

So again, I'm terribly sorry, that I can not accept the pull request with all the work you've put in there. I hope, I didn't ruin pull requests to js-zimbra for you now. :(

However, the timeout option is a quite a good idea, which is missing from js-zimbra currently. So, maybe you could get a fresh release and focus on implementing that?

Thanks again.

@barrydegraaff I seem to be missing write access to this repository now. So you have to close this for me. :)

**Comment by pbruna** [comment]
Hi @dploeger  No worries.
My bad about jQuery, your are right, it was based on Restler and we move to jQuery to make it work with the Browser. I guess we missed the move to Unirest.

Im going to give it a try now with Unirest.

By the way, thanks for your work, it had make my life a lot better.
Im using `js-zimbra` on another project: https://github.com/ZBoxApp/zimbra-admin-api-js

**Comment by dploeger** [comment]
Great! You're welcome.

**Pull request closed without merging**
